#!/usr/bin/env tsx
/**
 * Generate a fresh Ed25519 keypair for the settlement service.
 * Writes the result into .env.local (or appends if it exists).
 *
 * Usage: pnpm tg:keygen
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { generateTollgateKeyPair } from '@tollgate/shared'

async function main() {
  const envPath = resolve(process.cwd(), '.env.local')
  console.log('🔑 Generating Tollgate JWT keypair (Ed25519, EdDSA)...')

  const { privateKeyPem, publicKeyPem } = await generateTollgateKeyPair()
  const kid = `tg-${new Date().toISOString().slice(0, 7)}` // tg-YYYY-MM

  const block = `
# Generated by tg:keygen on ${new Date().toISOString()}
TOLLGATE_JWT_PRIVATE_KEY="${privateKeyPem.replace(/\n/g, '\\n')}"
TOLLGATE_JWT_PUBLIC_KEY="${publicKeyPem.replace(/\n/g, '\\n')}"
TOLLGATE_JWT_KID=${kid}
`.trim()

  if (existsSync(envPath)) {
    const existing = readFileSync(envPath, 'utf-8')
    const filtered = existing
      .split('\n')
      .filter(
        (line) =>
          !line.startsWith('TOLLGATE_JWT_PRIVATE_KEY=') &&
          !line.startsWith('TOLLGATE_JWT_PUBLIC_KEY=') &&
          !line.startsWith('TOLLGATE_JWT_KID='),
      )
      .join('\n')
    writeFileSync(envPath, `${filtered.trim()}\n\n${block}\n`, 'utf-8')
    console.log(`✅ Updated ${envPath}`)
  } else {
    writeFileSync(envPath, `${block}\n`, 'utf-8')
    console.log(`✅ Created ${envPath}`)
  }

  console.log(`   kid: ${kid}`)
  console.log(`   public key (first line): ${publicKeyPem.split('\n')[1]?.slice(0, 60)}...`)
  console.log('')
  console.log('Next: copy other secrets from .env.example into .env.local and run `pnpm dev`.')
}

main().catch((err) => {
  console.error('❌ keygen failed:', err)
  process.exit(1)
})
